### PR TITLE
Ability to add additional query string parameters to all methods

### PR DESCRIPTION
**Pull request by jondunning**
Additional query string parameter details are detailed here https://www.firebase.com/docs/rest/api/#section-query-parameters

Let me know if you need me to amend or change anything.

Thanks,

Jon

### CODE REVIEW

**Comment by zabawaba99** [comment]
Which query parameters are you using?

**Comment by MrGossett** [comment]
Would you be open to implementing each of the query parameters as methods, similar to [how we implemented the `auth` parameter](https://github.com/CloudCom/firego/blob/master/auth.go#L4)?

That would end up looking something like this:

``` go
Shallow()

// this would map to "format=export"
IncludePriority()

// since "print=pretty" doesn't quite make sense for this library, this would be the same as "print=silent"
Silent()

// these may be wrapped up into a Query() method
OrderBy()
LimitToFirst()
LimitToLast()
StartAt()
EndAt()
EqualTo()
```

Maybe you'd like to implement a subset of these?

**Comment by jondunning** [comment]
Like your structure better.

I'll get them implemented, will probably be tomorrow now.

**Comment by zabawaba99** [comment]
Looking forward to it. :+1:

**Comment by zabawaba99** [comment]
@jondunning Were you able to make any progress on this?

**Comment by zabawaba99** [comment]
Closed by #34

**Pull request closed without merging**
