### PR TITLE
Fix watch auth

### PR DESCRIPTION
**Pull request by mkmik**

### CODE REVIEW

**Comment by zabawaba99** [comment]
Can you add a test for this to prevent regression?

**Comment by mkmik** [comment]
Done, PTAL

**Comment by zabawaba99** [comment]
Looks good to me. Thanks for catching this one.

**Comment by mkmik** [comment]
Thanks for writing this library! :-)

**Comment by zabawaba99** [comment]
Absolutely, I have plans on beefing it up a bit more in the up coming weeks
so stay tuned! :dancer:

**Pull request merged**
