### PR TITLE
Support for OrderBy StartAt EndAt

### PR DESCRIPTION
**Pull request by crystalin**
There is probably a better way  to write it but this one is effective and easy to understand.

### CODE REVIEW

**Comment by crystalin** [comment]
Maybe it worth including that the OrderBy requires quotes, Ex:
...OrderBy("\"user_id\"").StartAt("123456").EndAt("123456")

**Comment by zabawaba99** [comment]
> Maybe it worth including that the OrderBy requires quotes

Looking at the [firebase docs](https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-ordered-data) it looks like we don't need the escaped quotes when using `OrderBy`

``` bash
curl 'https://dinosaur-facts.firebaseio.com/dinosaurs.json?orderBy="weight"&limitToLast=2&print=pretty' -v
*   Trying 104.197.145.189...
* Connected to dinosaur-facts.firebaseio.com (104.197.145.189) port 443 (#0)
* TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.firebaseio.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /dinosaurs.json?orderBy="weight"&limitToLast=2&print=pretty HTTP/1.1
> Host: dinosaur-facts.firebaseio.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 346
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
<
{
  "bruhathkayosaurus" : {
    "appeared" : -70000000,
    "height" : 25,
    "length" : 44,
    "order" : "saurischia",
    "vanished" : -70000000,
    "weight" : 135000
  },
  "triceratops" : {
    "appeared" : -68000000,
    "height" : 3,
    "length" : 8,
    "order" : "ornithischia",
    "vanished" : -66000000,
    "weight" : 11000
  }
}
```

**Comment by zabawaba99** [comment]
> There is probably a better way to write it but this one is effective and easy to understand.

I think that this is a great first step and get's the functionality out the door. Even if we decide to restructure this the API would end up staying the same. Could you please add a few tests similar to the [shallow test](https://github.com/CloudCom/firego/blob/master/firebase_test.go#L111)?

**Comment by crystalin** [comment]
I changed to use the param const as it was done for Shadow, and added some tests

**Comment by zabawaba99** [comment]
LGTM. Thanks for your contribution @crystalin

**Pull request merged**
